name: neopass_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cryptography: ^2.0.3
  cryptography_flutter: ^2.0.2
  convert: ^3.1.0
  provider: ^6.0.4
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  sqflite: ^2.2.6
  protobuf: ^2.1.0
  http:
  file_picker: ^5.2.6
  fixnum: ^1.1.0
  path: ^1.8.2
  logger: ^1.3.0

dev_dependencies:
  test: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: inter
      fonts:
        - asset: fonts/inter_regular.ttf
          weight: 400
        - asset: fonts/inter_light.ttf
          weight: 300
        - asset: fonts/inter_extra_light.ttf
          weight: 200

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
